### PR TITLE
fix: make umami stay up during migration and maintenance

### LINKED ISSUE #59: Don't apply Maintenance to Umami
When applying the maintenance, we might want to keep the Umami service around to measure the users landing on the maintenance page for example. 

Also since we do not work directly on the umami service, the need to put it in maintenance is weak.

### PR DESCRIPTION
**Pull request by spaenleh**
We want Umami to stay up when doing maintenance and migration.

This PR makes the necessary changes for this.
close #59

### CODE REVIEW

File: utils.ts [hunk 1]
```diff
@@ -86,7 +86,8 @@ export function validateInfraState(
 export function getInfraState(environment: EnvironmentConfig): {
   isMaintenanceActive: boolean;
   isDatabaseActive: boolean;
-  areServicesActive: boolean;
+  isUmamiActive: boolean;
+  areGraaspServicesActive: boolean;
   isMigrationActive: boolean;
```
Comment (pyphilia) [inline utils.ts:91]: I guess for now it's okay, but if we think of adding even more of them, maybe it's easier to read:
```
isActive/active: {
  maintenance: boolean,
  database: boolean,
  umami: boolean,
  ...
}
```

**Review by pyphilia — APPROVED** [review]
LGTM :fishsticks:
